### ISSUE TITLE
Importing the button causes an error "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by ShunyaWatanabe** [zendeskgarden/react-components#782]
## Expectations

I can import the button without an error.

## Reality
```
RangeError: Maximum call stack size exceeded
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1162:19)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
    at mixinDeep (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1173:11)
    at mixin (/Users/swatanabe025/Desktop/private/portfolio/node_modules/styled-components/dist/styled-components.cjs.js:1156:5)
```

## Steps to Reproduce

1. Use `yarn create next-app` to start your project
2. `yarn create next-app` on terminal
3. `yarn add @zendeskgarden/react-buttons` on terminal 
4. `yarn add prop-types styled-components @zendeskgarden/react-theming` on terminal
5. Add this line of code in any js file `import { Button } from '@zendeskgarden/react-buttons';`

### Fine Print

- Component:  "@zendeskgarden/react-buttons"
- Version:  "^8.14.0"
- Browsers: google chrome

**Comment by austin94** [comment]
@ShunyaWatanabe did you find a resolution for this?

**Comment by ShunyaWatanabe** [comment]
@austin94 It started working somehow... Thank you for the comment!

**Comment by ShunyaWatanabe** [comment]
Actually i started getting the same error. If I comment out 

```
import Button from 'components/Button';
```

My pages render fine, but with the import, it gives me an error below.

<img width="300" alt="Screen Shot 2020-06-19 at 8 48 04 PM" src="https://user-images.githubusercontent.com/25846438/85159197-372c0580-b26e-11ea-994e-488f2efc2604.png">

The related repo is this https://github.com/ShunyaWatanabe/portfolio

**Comment by austin94** [comment]
Interesting. Could you try this with the latest `v4` release of styled-components? Looking through their repo it seems there are issues with v5 usage and some server-side rendering environments.

**Comment by austin94** [comment]
FWIW we are currently using `styled-components@v5` and `zendeskgarden/react@v8` with Gatsby server-side rendering successfully.

**Comment by ShunyaWatanabe** [comment]
I downgraded `styled-components` to v4.4.1 and it seems to be working fine! Thank you @austin94.

**Comment by fredericrous** [comment]
I can reproduce this error with the Dropdown component

on garden 8.39.0, styled-components 5.3.3 and NextJS 12.0.7

This is probably an issue with server sider rendering.

the code that causes problems

```
 <Dropdown
      onSelect={(item) => {
        switch (item) {
          case 'help':
            window.open('https://help-newswire.storyful.com/en/', '_blank', 'noopener');
            break;
          default:
            break;
        }
      }}
      onStateChange={(options) => Object.prototype.hasOwnProperty.call(options, 'isOpen') && setRotated(options.isOpen)}
    >
      <Trigger>
        <div>test</div>
      </Trigger>
      <Menu className={styles.menu}>
        <Item value="help">
           Help Centre
        </Item>
      </Menu>
    </Dropdown>
```

at some point I was able to fix the issue by adding the following attribute to the Dropdown element

```
      downshiftProps={{
        id: 'menu', 
      }}
```

however that just worked for a time and it's not working anymore
